############################################################################
## DOCKER COMPOSE FILE                                                    ##
## Author: Frederic Depuydt                                               ##
## Mail: frederic.depuydt@outlook.com                                     ##
##                                                                        ##
## Contains:                                                              ##
## - MARIADB                                                              ##
## - PhpMyAdmin                                                           ##
## - Adminer                                                              ##
##                                                                        ##
############################################################################


version: '3.7'

services:
  mariadb:
    container_name: mariadb
    image: linuxserver/mariadb
    restart: unless-stopped
    networks:
      - db
    volumes:
      - mariadb-conf:/config
      - mariadb-data:/var/lib/mysql
    env_file: ./config/.env
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    networks:
      - web
      - db
    env_file: ./config/.env
    environment:
       - PMA_HOST=mariadb.db
       #- PMA_ARBITRARY=1
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"

      - "traefik.http.routers.phpmyadmin.entrypoints=websecure"
      - "traefik.http.routers.phpmyadmin.rule=Host(`phpmyadmin.${DOMAINNAME}`)"
      - "traefik.http.routers.phpmyadmin.tls.certResolver=tls"
      - "traefik.http.routers.phpmyadmin.service=phpmyadmin"
      - "traefik.http.services.phpmyadmin.loadbalancer.server.port=80"

  adminer:
    container_name: adminer
    image: adminer
    restart: unless-stopped
    networks:
      - web
      - db
    env_file: ./config/.env
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"

      - "traefik.http.routers.adminer.entrypoints=websecure"
      - "traefik.http.routers.adminer.rule=Host(`adminer.${DOMAINNAME}`)"
      - "traefik.http.routers.adminer.tls.certResolver=tls"
      - "traefik.http.routers.adminer.service=adminer"
      - "traefik.http.services.adminer.loadbalancer.server.port=8080"

networks:
  web:
    external: true
  db:
    external: true

volumes:
  mariadb-conf:
    name: mariadb-conf
  mariadb-data:
    name: mariadb-data
