############################################################################
## DOCKER COMPOSE FILE                                                    ##
## Author: Frederic Depuydt                                               ##
## Mail: frederic.depuydt@outlook.com                                     ##
##                                                                        ##
## Contains:                                                              ##
## - MARIADB                                                              ##
## - PhpMyAdmin                                                           ##
## - Adminer                                                              ##
##                                                                        ##
############################################################################


version: '3.7'

services:
  mariadb:
    container_name: database-mariadb
    image: linuxserver/mariadb
    restart: always
    ports:
      - 3306:3306
    networks:
      - db
    volumes:
      - database-mariadb-conf:/config
      - database-mariadb-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=IMOCCAPE
      - TZ=Europe/Brussels
      #- PUID=1000
      #- PGID=1000
      #- MYSQL_DATABASE=phpmyadin
      #- MYSQL_USER=user
      #- MYSQL_PASSWORD=1234
      #- MYSQL_DATABASE=logs
      #- MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PW}

  phpmyadmin:
    container_name: database-phpmyadmin
    image: sk278/phpmyadmin-armhf:4.8.3
    restart: always
    ports:
      - 8080:80
    networks:
      - web
      - db
    environment:
       - PMA_HOST=database-mariadb
       - MYSQL_USERNAME=root
       - MYSQL_ROOT_PASSWORD=IMOCCAPE
       #- PMA_ARBITRARY=1
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"

      - "traefik.http.routers.phpmyadmin.entrypoints=websecure"
      - "traefik.http.routers.phpmyadmin.rule=Host(`phpmyadmin.${DOMAINNAME}`)"
      - "traefik.http.routers.phpmyadmin.tls.certResolver=tls"
      - "traefik.http.routers.phpmyadmin.service=phpmyadmin"
      - "traefik.http.services.phpmyadmin.loadbalancer.server.port=80"

  adminer:
    container_name: database-adminer
    image: adminer
    restart: always
    networks:
      - web
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"

      - "traefik.http.routers.adminer.entrypoints=websecure"
      - "traefik.http.routers.adminer.rule=Host(`adminer.${DOMAINNAME}`)"
      - "traefik.http.routers.adminer.tls.certResolver=tls"
      - "traefik.http.routers.adminer.service=adminer"
      - "traefik.http.services.adminer.loadbalancer.server.port=8080"

networks:
  web:
    external: true
  db:
    external: true
  dns:
    external: true

volumes:
  database-mariadb-conf:
    name: database-mariadb-conf
  database-mariadb-data:
    name: database-mariadb-data
  database-influxdb-data:
    name: database-influxdb-data
